# Generated by Django 5.2.17 on 2026-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum number of emails to dispatch per daily batch.",
                    ),
                ),
                (
                    "delay_seconds",
                    models.FloatField(
                        default=1.5,
                        help_text="Seconds delay between consecutive emails to prevent rate-limiting.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Sent", "Sent"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="Inquiry Regarding Software Engineer Opportunities",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="Hello Hiring Team at {{ company_name }},\n\nI hope you are doing well.\n\nI am a recent engineering graduate currently looking for Software Engineer or fresher-level opportunities. I wanted to ask if there are any relevant openings available at your company.\n\nI would be grateful if you could consider my profile for any suitable opportunities.\n\nThank you for your time.\n\nRegards,\nDheeraj",
                        help_text="Use {{ company_name }} as a placeholder for the company's name.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
    ]
