# Generated by Django 5.2.17 on 2026-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="sending_mode",
            field=models.CharField(
                choices=[
                    ("safe", "🛡️ Safe Mode (Gmail-Friendly)"),
                    ("normal", "⚡ Normal Mode"),
                    ("custom", "⚙️ Custom"),
                ],
                default="safe",
                help_text="Safe Mode uses Gmail-friendly limits to avoid spam filters.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="daily_limit",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Maximum number of emails to dispatch per daily batch.",
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="delay_seconds",
            field=models.FloatField(
                default=3.0,
                help_text="Seconds delay between consecutive emails to prevent rate-limiting.",
            ),
        ),
    ]
