# Generated by Django 5.2.17 on 2026-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_appsettings_sending_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional contact person / HR name.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body",
            field=models.TextField(
                default="Hello {{ name }},\n\nHope you are doing well.\n\nMy name is Dheeraj, and I am currently looking for an opportunity as a Software Engineer/Fresher. I wanted to check if there are any openings available at {{ company_name }}.\n\nI have been working on my technical skills and projects and would be happy to be considered for any suitable role.\n\nYou can view my resume here:\nhttps://drive.google.com/file/d/1G_qTw4hwmWoY9QvmH1935kC4t5iltl32/view?usp=drive_link\n\nPlease let me know if there is any opportunity that matches my profile.\n\nThank you for your time.\n\nBest regards,\nDheeraj",
                help_text="Use {{ name }} for recipient/HR name and {{ company_name }} for company name.",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(
                default="Opportunity as Software Engineer/Fresher", max_length=255
            ),
        ),
    ]
