# Generated by Django 5.2.17 on 2026-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0003_contact_name_alter_emailtemplate_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_person",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional. HR/Recruiter name (e.g. 'Gargi'). If blank, greeting defaults to 'Hello,'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body",
            field=models.TextField(
                default="Hello {{ contact_person }},\n\nHope you are doing well.\n\nMy name is Dheeraj, and I am currently looking for an opportunity as a Software Engineer/Fresher. I wanted to check if there are any openings available at {{ company_name }}.\n\nI have been working on my technical skills and projects and would be happy to be considered for any suitable role.\n\nYou can view my resume here:\nhttps://drive.google.com/file/d/1G_qTw4hwmWoY9QvmH1935kC4t5iltl32/view?usp=drive_link\n\nPlease let me know if there is any opportunity that matches my profile.\n\nThank you for your time.\n\nBest regards,\nDheeraj",
                help_text="Use {{ company_name }} for company name and {{ contact_person }} for HR/recruiter name (auto-removed if blank).",
            ),
        ),
    ]
